### ISSUE TITLE
error Cannot find module './src/fileNameCachePlugin'

### ISSUE THREAD

**Issue by snowlotus** [fingerpan/vue-cli-plugin-dll#17]
error info 
```
ERROR  Error: Cannot find module './src/fileNameCachePlugin'

Error: Cannot find module './src/fileNameCachePlugin'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at dll (/Users/snowdrop/Desktop/pahhb_vue3_ui/node_modules/@lynzz/vue-cli-plugin-dll2/service.js:60:37)
    at Service.run (/Users/snowdrop/Desktop/pahhb_vue3_ui/node_modules/@vue/cli-service/lib/Service.js:219:12)
    at Object.<anonymous> (/Users/snowdrop/Desktop/pahhb_vue3_ui/node_modules/@vue/cli-service/bin/vue-cli-service.js:36:9)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:774:12)
    at executeUserCode (internal/bootstrap/node.js:499:15)
    at startMainThreadExecution (internal/bootstrap/node.js:436:3)
```

**Comment by fingerpan** [comment]
感谢反馈，可以告知一下你的node版本吗？
还有另外一个问题，你下载的并不是我的模块，而是fork我项目的另外一个项目。
我的模块名称是 vue-cli-plugin-dll。而你下载的是@lynzz/vue-cli-plugin-dll2。
你应该 vue  add dll

**Comment by Ruby-wurui** [comment]
ERROR  Error: Cannot find module 'vue-loader/lib/plugin'
Error: Cannot find module 'vue-loader/lib/plugin'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at /Users/yubh/haoweilai/cli3-test/node_modules/vue-cli-plugin-dll/service.js:89:35
    at Service.run (/Users/yubh/haoweilai/cli3-test/node_modules/@vue/cli-service/lib/Service.js:221:12)
    at Object.<anonymous> (/Users/yubh/haoweilai/cli3-test/node_modules/@vue/cli-service/bin/vue-cli-service.js:36:9)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:279:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:696:3)

我用的是 node 10

执行 npm run dll

vue.config 配置:
  pluginOptions: {
    dll: {
      entry: ['vue', 'vue-route', 'axios', 'vuex', 'vux'],
      output: path.join(__dirname, './public/dll'),
      inject: true,
      open: process.env.NODE_ENV === 'production'
    }
  },

**Comment by fingerpan** [comment]
@yubignhua 你的 vue-loader 版本多少

**Comment by yubignhua** [comment]
> @yubignhua 你的 vue-loader 版本多少

    "vue-loader": "14.2.3",

**Comment by Ruby-wurui** [comment]
@fingerpan "vue-loader": "14.2.3",

**Comment by fingerpan** [comment]
@yubignhua 你应该升级一下你的vue-loader。
