### ISSUE TITLE
    "vue-loader": "^15.7.0",

### ISSUE THREAD

**Issue by Ruby-wurui** [fingerpan/vue-cli-plugin-dll#21]
ERROR  Error: Build failed with errors.
Error: Build failed with errors.
    at webpack (/Users/yubh/haoweilai/mobile-h5-user/node
_modules/vue-cli-plugin-dll/service.js:122:39)
    at finalCallback (/Users/yubh/haoweilai/mobile-h5-use
r/node_modules/webpack/lib/Compiler.js:214:39)
    at hooks.done.callAsync.err (/Users/yubh/haoweilai/mo
bile-h5-user/node_modules/webpack/lib/Compiler.js:230:13)
    at AsyncSeriesHook.eval [as callAsync] (eval at creat
e (/Users/yubh/haoweilai/mobile-h5-user/node_modules/tapa
ble/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/yubh/haowe
ilai/mobile-h5-user/node_modules/tapable/lib/Hook.js:154:
20)
    at onCompiled (/Users/yubh/haoweilai/mobile-h5-user/n
ode_modules/webpack/lib/Compiler.js:228:21)
    at hooks.afterCompile.callAsync.err (/Users/yubh/haoweilai/mobile-h5-user/node_modules/webpack/lib/Compiler.js:556:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/yubh/haoweilai/mobile-h5-user/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/yubh/haoweilai/mobile-h5-user/node_modules/tapable/lib/Hook.js:154:20)
    at compilation.seal.err (/Users/yubh/haoweilai/mobile-h5-user/node_modules/webpack/lib/Compiler.js:553:30)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/yubh/haoweilai/mobile-h5-user/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/yubh/haoweilai/mobile-h5-user/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.optimizeAssets.callAsync.err (/Users/yubh/haoweilai/mobile-h5-user/node_modules/webpack/lib/Compilation.js:1323:35)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/yubh/haoweilai/mobile-h5-user/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/yubh/haoweilai/mobile-h5-user/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.optimizeChunkAssets.callAsync.err (/Users/yubh/haoweilai/mobile-h5-user/node_modules/webpack/lib/Compilation.js:1314:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mobile-h5-user@0.1.1 dll: `vue-cli-service dll`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mobile-h5-user@0.1.1 dll script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/yubh/.npm/_logs/2019-03-21T15_26_21_952Z-debug.log

**Comment by fingerpan** [comment]
这个报错并不是vue-loader的问题，是webpack打包出现报错，你的webpack版本是多少？ 能否提供一下具体的配置，你在vue.config.js有没有做其他操作？
