### ISSUE TITLE
不支持pnpm?

### ISSUE THREAD

**Issue by CongAn** [fingerpan/vue-cli-plugin-dll#35]
```
This dependency was not found:

* vue-route in dll dll

To install it, you can run: npm install --save vue-route

 ERROR  Error: Build failed with errors.
Error: Build failed with errors.
    at webpack (/Users/Anker/Develop/slicejobs/alg-ajx-mobile/node_modules/.registry.npm.taobao.org/vue-cli-plugin-dll/1.1.9_@vue+cli-service@3.10.0/node_modules/vue-cli-plugin-dll/service.js:125:39)
    at finalCallback (/Users/Anker/Develop/slicejobs/alg-ajx-mobile/node_modules/.registry.npm.taobao.org/webpack/4.28.4_webpack@4.28.4/node_modules/webpack/lib/Compiler.js:214:39)
    at hooks.done.callAsync.err (/Users/Anker/Develop/slicejobs/alg-ajx-mobile/node_modules/.registry.npm.taobao.org/webpack/4.28.4_webpack@4.28.4/node_modules/webpack/lib/Compiler.js:230:13)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/Anker/Develop/slicejobs/alg-ajx-mobile/node_modules/.registry.npm.taobao.org/tapable/1.1.3/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/Anker/Develop/slicejobs/alg-ajx-mobile/node_modules/.registry.npm.taobao.org/tapable/1.1.3/node_modules/tapable/lib/Hook.js:154:20)
    at onCompiled (/Users/Anker/Develop/slicejobs/alg-ajx-mobile/node_modules/.registry.npm.taobao.org/webpack/4.28.4_webpack@4.28.4/node_modules/webpack/lib/Compiler.js:228:21)
    at hooks.afterCompile.callAsync.err (/Users/Anker/Develop/slicejobs/alg-ajx-mobile/node_modules/.registry.npm.taobao.org/webpack/4.28.4_webpack@4.28.4/node_modules/webpack/lib/Compiler.js:556:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/Anker/Develop/slicejobs/alg-ajx-mobile/node_modules/.registry.npm.taobao.org/tapable/1.1.3/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/Anker/Develop/slicejobs/alg-ajx-mobile/node_modules/.registry.npm.taobao.org/tapable/1.1.3/node_modules/tapable/lib/Hook.js:154:20)
    at compilation.seal.err (/Users/Anker/Develop/slicejobs/alg-ajx-mobile/node_modules/.registry.npm.taobao.org/webpack/4.28.4_webpack@4.28.4/node_modules/webpack/lib/Compiler.js:553:30)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/Anker/Develop/slicejobs/alg-ajx-mobile/node_modules/.registry.npm.taobao.org/tapable/1.1.3/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/Anker/Develop/slicejobs/alg-ajx-mobile/node_modules/.registry.npm.taobao.org/tapable/1.1.3/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.optimizeAssets.callAsync.err (/Users/Anker/Develop/slicejobs/alg-ajx-mobile/node_modules/.registry.npm.taobao.org/webpack/4.28.4_webpack@4.28.4/node_modules/webpack/lib/Compilation.js:1323:35)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/Anker/Develop/slicejobs/alg-ajx-mobile/node_modules/.registry.npm.taobao.org/tapable/1.1.3/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/Anker/Develop/slicejobs/alg-ajx-mobile/node_modules/.registry.npm.taobao.org/tapable/1.1.3/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.optimizeChunkAssets.callAsync.err (/Users/Anker/Develop/slicejobs/alg-ajx-mobile/node_modules/.registry.npm.taobao.org/webpack/4.28.4_webpack@4.28.4/node_modules/webpack/lib/Compilation.js:1314:32)
 ERROR  Command failed with exit code 1.

```

**Comment by fingerpan** [comment]
目前不支持
